// Mock data + i18n. Exposed as window.AppData for other scripts.

const TRANSLATIONS = {
  en: {
    appName: "Smarties",
    tag: "Care, made simpler",
    nav: { home: "Home", trips: "Trips", profile: "Profile" },

    // onboarding
    ob: {
      step: "Step",
      of: "of",
      back: "Back",
      next: "Next",
      q1Title: "Is your loved one a Singapore Citizen or PR?",
      q1Sub: "Subsidies are available for Citizens and Permanent Residents.",
      yes: "Yes",
      no: "No, neither",
      q2Title: "How old are they?",
      q2Sub: "Most subsidised schemes start from age 60.",
      years: "years old",
      q3Title: "Can they get to appointments on their own?",
      q3Sub: "This helps us pick the right kind of vehicle.",
      mobIndep: "Yes, on their own",
      mobHelp: "Needs some help",
      mobChair: "Wheelchair only",
      q4Title: "Roughly, household income per person each month?",
      q4Sub: "Used only to estimate your subsidy. Nothing is saved.",
      inc1: "Under $1,200",
      inc2: "$1,200 – $2,800",
      inc3: "Over $2,800",
      inc4: "Not sure",
      verdictTitle: "Likely eligible.",
      verdictSub: "Based on what you shared, you should qualify for help.",
      estSubsidy: "Estimated subsidy",
      coPay: "Co-pay around",
      perRound: "per round trip",
      findRide: "Find a ride",
      whyAsk: "Why we ask",
    },

    // trip new
    tn: {
      title: "Book a ride",
      subtitle: "Compare your options before you book.",
      detailsTitle: "Trip details",
      home: "Home",
      hospital: "Hospital",
      when: "Pickup",
      edit: "Edit",
      change: "Change",
      grabHead: "Grab / Taxi",
      grabPrice: "≈ $70–$80",
      grabBullets: ["Door-to-door", "No escort", "Books in 5 min"],
      grabBtn: "Book Grab",
      metHead: "MET (subsidised)",
      metBadge: "Subsidised",
      metBullets: ["Wheelchair-accessible", "Door-to-door"],
      metBtn: "Book MET",
      youSave: "You save",
      perTrip: "per trip",
      yearly: "≈ $1,100 a year at 4 trips / month",
      compareTitle: "Side by side",
      whyMET: "Why MET costs less",
      whyMETBody:
        "Government and community partners cover most of the fare for eligible seniors. You only pay the small co-pay shown above.",
    },

    // providers
    pv: {
      title: "Choose a provider",
      subtitle: "Three providers serve your area. Pick whichever feels right — you can switch later.",
      serves: "Serves your area",
      coPay: "Co-pay",
      response: "Replies in",
      choose: "Choose",
      foot: "Don't worry — you can change providers any time.",
    },

    // apply
    ap: {
      sentTo: "Confirmed with",
      reassure: "Your driver and escort have been assigned. You'll get a reminder the night before pickup.",
      ref: "Reference",
      view: "View trip status",
      addCal: "Add to calendar",
      whatNext: "What happens next",
      n1: "Provider has confirmed your request",
      n2: "Driver and escort are assigned",
      n3: "Reminder + driver tracking the night before",
    },

    // tracker
    tk: {
      title: "Live trip status",
      eta: "ETA",
      drvAssigned: "Driver assigned",
      driver: "Driver",
      escort: "Escort",
      vehicle: "Vehicle",
      mapPlaceholder: "Live map will appear here once driver is en route.",
      notify: "Notify me when home safe",
      notifySub: "We'll send you an SMS the moment they arrive.",
      stages: [
        "Application sent",
        "Confirmed by provider",
        "Driver assigned",
        "En route to pickup",
        "Senior boarded",
        "Arrived at hospital",
      ],
      contact: "Contact provider",
      cancel: "Cancel trip",
      reqAt: "Requested",
      arr: "Arrives",
    },

    // home
    hm: {
      hi: "Good morning,",
      caring: "Caring for",
      next: "Your next trip",
      nothing: "No trips coming up.",
      bookNew: "Book a new ride",
      quick: "Quick actions",
      checkElig: "Check eligibility",
      manageProf: "Senior's profile",
      tips: "Things you might need",
      tip1Title: "Bring along",
      tip1Body: "IC, appointment letter, regular medication.",
      tip2Title: "Tell the escort",
      tip2Body: "Any allergies, mobility limits or hearing aid use.",
      saved: "saved this year",
    },

    // trips list
    tl: {
      title: "Your trips",
      upcoming: "Upcoming",
      past: "Past",
      empty: "No trips yet.",
    },

    // profile
    pr: {
      title: "Profile",
      caregiver: "Caregiver",
      senior: "Senior under your care",
      lang: "Language",
      acc: "Accessibility",
      bigText: "Larger text",
      ack: "Acknowledgement",
      version: "Smarties demo · v0.4 · prototype",
      changeElig: "Re-check eligibility",
      eligNote: "Subsidy estimate",
    },

    common: {
      step: "Step",
      progress: "Progress",
      a11yBack: "Go back",
      cancel: "Cancel",
      confirm: "Confirm",
    },
  },

  zh: {
    appName: "Smarties",
    tag: "照护，更简单",
    nav: { home: "首页", trips: "行程", profile: "我的" },
    ob: {
      step: "第", of: "/",
      back: "返回", next: "下一步",
      q1Title: "您的家人是新加坡公民或永久居民吗？",
      q1Sub: "公民和永久居民可申请补贴。",
      yes: "是", no: "都不是",
      q2Title: "他/她今年几岁？",
      q2Sub: "大部分补贴计划从 60 岁起。",
      years: "岁",
      q3Title: "他/她能独自去看诊吗？",
      q3Sub: "我们会按此安排车辆。",
      mobIndep: "可以，自己来",
      mobHelp: "需要一些协助",
      mobChair: "需轮椅出行",
      q4Title: "家庭人均月收入大约？",
      q4Sub: "仅用于估算补贴，不会保存。",
      inc1: "少于 $1,200",
      inc2: "$1,200 – $2,800",
      inc3: "超过 $2,800",
      inc4: "不确定",
      verdictTitle: "看起来符合条件",
      verdictSub: "根据您的回答，您应该可以获得帮助。",
      estSubsidy: "预计补贴",
      coPay: "自付约",
      perRound: "每趟往返",
      findRide: "查找车辆",
      whyAsk: "为什么这样问",
    },
    tn: {
      title: "预订车辆",
      subtitle: "预订前比较一下您的选择。",
      detailsTitle: "行程详情",
      home: "出发", hospital: "目的地", when: "接送时间",
      edit: "编辑", change: "更改",
      grabHead: "Grab / 德士",
      grabPrice: "≈ $70–$80",
      grabBullets: ["门到门", "无陪同", "5 分钟可叫车"],
      grabBtn: "叫 Grab",
      metHead: "MET（补贴）",
      metBadge: "已补贴",
      metBullets: ["轮椅可上下", "门到门接送"],
      metBtn: "预订 MET",
      youSave: "您节省",
      perTrip: "每趟",
      yearly: "≈ 每年 $1,100（每月 4 趟）",
      compareTitle: "并排对比",
      whyMET: "为什么 MET 更便宜",
      whyMETBody: "政府和社区伙伴为合资格的年长者承担大部分车资。您只需支付以上小额自付费。",
    },
    pv: {
      title: "选择服务方",
      subtitle: "三家服务方覆盖您所在地区。先选一家，之后还可以更换。",
      serves: "覆盖您所在地区",
      coPay: "自付",
      response: "回复约",
      choose: "选择",
      foot: "别担心，您随时可以更换服务方。",
    },
    ap: {
      sentTo: "已确认服务方",
      reassure: "司机与陪同员已安排妥当。出行前一晚我们会再发提醒。",
      ref: "参考号",
      view: "查看行程状态",
      addCal: "加入日历",
      whatNext: "接下来",
      n1: "服务方已确认您的申请",
      n2: "司机与陪同员已分配",
      n3: "出行前一晚发送提醒，并开始实时追踪",
    },
    tk: {
      title: "实时行程",
      eta: "预计到达",
      drvAssigned: "已分配司机",
      driver: "司机", escort: "陪同员", vehicle: "车辆",
      mapPlaceholder: "司机出发后这里会显示实时地图。",
      notify: "到家时通知我",
      notifySub: "他们一到家我们就发短信。",
      stages: [
        "申请已发送",
        "服务方已确认",
        "已分配司机",
        "正在前往接送点",
        "长者已上车",
        "已抵达医院",
      ],
      contact: "联系服务方",
      cancel: "取消行程",
      reqAt: "申请于",
      arr: "抵达",
    },
    hm: {
      hi: "早上好，",
      caring: "正在照顾",
      next: "下一趟行程",
      nothing: "暂无即将出行的行程。",
      bookNew: "预订新行程",
      quick: "快捷操作",
      checkElig: "查看补贴资格",
      manageProf: "长者档案",
      tips: "可能用得上",
      tip1Title: "出门带上",
      tip1Body: "身份证、预约信、常服药物。",
      tip2Title: "告诉陪同员",
      tip2Body: "过敏、行动限制或助听器使用情况。",
      saved: "今年已省",
    },
    tl: { title: "您的行程", upcoming: "即将", past: "过去", empty: "暂无行程。" },
    pr: {
      title: "我的",
      caregiver: "照护者",
      senior: "您照顾的长者",
      lang: "语言",
      acc: "辅助功能",
      bigText: "更大字号",
      ack: "鸣谢",
      version: "Smarties 演示 · v0.4 · 原型",
      changeElig: "重新评估资格",
      eligNote: "补贴估算",
    },
    common: { step: "步骤", progress: "进度", a11yBack: "返回", cancel: "取消", confirm: "确认" },
  },

  ms: {
    appName: "Smarties",
    tag: "Penjagaan, lebih mudah",
    nav: { home: "Utama", trips: "Perjalanan", profile: "Profil" },
    ob: {
      step: "Langkah", of: "drpd",
      back: "Kembali", next: "Seterusnya",
      q1Title: "Adakah orang tersayang anda Warganegara atau PR Singapura?",
      q1Sub: "Subsidi tersedia untuk Warganegara dan Penduduk Tetap.",
      yes: "Ya", no: "Bukan kedua-duanya",
      q2Title: "Berapa umur mereka?",
      q2Sub: "Kebanyakan subsidi bermula dari umur 60 tahun.",
      years: "tahun",
      q3Title: "Boleh mereka pergi temujanji sendiri?",
      q3Sub: "Ini membantu kami pilih kenderaan yang sesuai.",
      mobIndep: "Ya, sendiri",
      mobHelp: "Perlukan sedikit bantuan",
      mobChair: "Hanya dengan kerusi roda",
      q4Title: "Anggaran pendapatan isi rumah per orang sebulan?",
      q4Sub: "Hanya untuk anggaran subsidi. Tiada data disimpan.",
      inc1: "Bawah $1,200",
      inc2: "$1,200 – $2,800",
      inc3: "Lebih $2,800",
      inc4: "Tidak pasti",
      verdictTitle: "Berkemungkinan layak.",
      verdictSub: "Berdasarkan jawapan anda, anda patut mendapat bantuan.",
      estSubsidy: "Anggaran subsidi",
      coPay: "Bayaran sekitar",
      perRound: "setiap perjalanan pergi-balik",
      findRide: "Cari kenderaan",
      whyAsk: "Mengapa kami tanya",
    },
    tn: {
      title: "Tempah perjalanan",
      subtitle: "Bandingkan pilihan sebelum tempah.",
      detailsTitle: "Butiran perjalanan",
      home: "Rumah", hospital: "Hospital", when: "Pickup",
      edit: "Edit", change: "Tukar",
      grabHead: "Grab / Teksi",
      grabPrice: "≈ $70–$80",
      grabBullets: ["Pintu ke pintu", "Tiada pengiring", "Tempah dlm 5 min"],
      grabBtn: "Tempah Grab",
      metHead: "MET (subsidi)",
      metBadge: "Disubsidi",
      metBullets: ["Mesra kerusi roda", "Pintu ke pintu"],
      metBtn: "Tempah MET",
      youSave: "Anda jimat",
      perTrip: "setiap perjalanan",
      yearly: "≈ $1,100 setahun (4 trip/bulan)",
      compareTitle: "Bandingan",
      whyMET: "Kenapa MET lebih murah",
      whyMETBody: "Kerajaan dan rakan komuniti menanggung sebahagian besar tambang untuk warga emas yang layak. Anda hanya bayar bayaran kecil di atas.",
    },
    pv: {
      title: "Pilih penyedia",
      subtitle: "Tiga penyedia berkhidmat di kawasan anda. Anda boleh tukar kemudian.",
      serves: "Berkhidmat di kawasan anda",
      coPay: "Bayaran",
      response: "Balasan dlm",
      choose: "Pilih",
      foot: "Anda boleh tukar penyedia bila-bila masa.",
    },
    ap: {
      sentTo: "Disahkan dengan",
      reassure: "Pemandu dan pengiring anda telah ditetapkan. Anda akan terima peringatan malam sebelum pickup.",
      ref: "Rujukan",
      view: "Lihat status perjalanan",
      addCal: "Tambah ke kalendar",
      whatNext: "Apa selepas ini",
      n1: "Penyedia telah sahkan permohonan",
      n2: "Pemandu dan pengiring sudah ditetapkan",
      n3: "Peringatan + jejak pemandu malam sebelumnya",
    },
    tk: {
      title: "Status perjalanan",
      eta: "Anggaran tiba",
      drvAssigned: "Pemandu ditetapkan",
      driver: "Pemandu", escort: "Pengiring", vehicle: "Kenderaan",
      mapPlaceholder: "Peta langsung akan muncul apabila pemandu dlm perjalanan.",
      notify: "Beritahu saya bila selamat sampai rumah",
      notifySub: "Kami hantar SMS sebaik sahaja mereka tiba.",
      stages: [
        "Permohonan dihantar",
        "Disahkan oleh penyedia",
        "Pemandu ditetapkan",
        "Dlm perjalanan ke pickup",
        "Warga emas naik",
        "Tiba di hospital",
      ],
      contact: "Hubungi penyedia",
      cancel: "Batal perjalanan",
      reqAt: "Dimohon",
      arr: "Tiba",
    },
    hm: {
      hi: "Selamat pagi,",
      caring: "Menjaga",
      next: "Perjalanan seterusnya",
      nothing: "Tiada perjalanan akan datang.",
      bookNew: "Tempah perjalanan baru",
      quick: "Tindakan pantas",
      checkElig: "Semak kelayakan",
      manageProf: "Profil warga emas",
      tips: "Mungkin anda perlu",
      tip1Title: "Bawa bersama",
      tip1Body: "IC, surat temujanji, ubat biasa.",
      tip2Title: "Beritahu pengiring",
      tip2Body: "Alergi, kekangan mobiliti atau penggunaan alat bantu pendengaran.",
      saved: "dijimatkan tahun ini",
    },
    tl: { title: "Perjalanan anda", upcoming: "Akan datang", past: "Lepas", empty: "Belum ada perjalanan." },
    pr: {
      title: "Profil",
      caregiver: "Penjaga",
      senior: "Warga emas dlm jagaan",
      lang: "Bahasa",
      acc: "Kebolehcapaian",
      bigText: "Saiz teks lebih besar",
      ack: "Penghargaan",
      version: "Smarties demo · v0.4 · prototaip",
      changeElig: "Semak semula kelayakan",
      eligNote: "Anggaran subsidi",
    },
    common: { step: "Langkah", progress: "Kemajuan", a11yBack: "Kembali", cancel: "Batal", confirm: "Sahkan" },
  },

  ta: {
    appName: "Smarties",
    tag: "எளிமையான பராமரிப்பு",
    nav: { home: "முகப்பு", trips: "பயணங்கள்", profile: "சுயவிவரம்" },
    ob: {
      step: "படி", of: "/",
      back: "பின்", next: "அடுத்து",
      q1Title: "உங்கள் உறவினர் சிங்கப்பூர் குடிமகனா/PR ஆ?",
      q1Sub: "குடிமக்களுக்கும் PR-களுக்கும் மானியம் உண்டு.",
      yes: "ஆம்", no: "இல்லை",
      q2Title: "அவர்களின் வயது?",
      q2Sub: "பெரும்பாலான திட்டங்கள் 60 வயதிலிருந்து தொடங்கும்.",
      years: "வயது",
      q3Title: "அவர்களே சந்திப்புக்குச் செல்ல முடியுமா?",
      q3Sub: "சரியான வாகனத்தைத் தேர்வு செய்ய இது உதவும்.",
      mobIndep: "ஆம், தனியாக",
      mobHelp: "சிறிது உதவி தேவை",
      mobChair: "சக்கர நாற்காலி மட்டும்",
      q4Title: "ஒருவருக்கான மாதவருமானம் தோராயமாக?",
      q4Sub: "மானியக் கணக்கீட்டிற்கு மட்டுமே. சேமிக்கப்படாது.",
      inc1: "$1,200-க்கு கீழ்",
      inc2: "$1,200 – $2,800",
      inc3: "$2,800-க்கு மேல்",
      inc4: "தெரியாது",
      verdictTitle: "தகுதி உண்டு போன்றது.",
      verdictSub: "உங்கள் பதில்களின்படி உதவி கிடைக்கும்.",
      estSubsidy: "தோராய மானியம்",
      coPay: "சுய பங்கு",
      perRound: "ஒரு போக்கு–வரத்து பயணத்திற்கு",
      findRide: "வாகனம் தேடு",
      whyAsk: "ஏன் கேட்கிறோம்",
    },
    tn: {
      title: "பயணம் முன்பதிவு",
      subtitle: "முன்பதிவு செய்வதற்கு முன் ஒப்பிடுங்கள்.",
      detailsTitle: "பயண விவரங்கள்",
      home: "வீடு", hospital: "மருத்துவமனை", when: "ஏற்றுவது",
      edit: "திருத்து", change: "மாற்று",
      grabHead: "Grab / டாக்ஸி",
      grabPrice: "≈ $70–$80",
      grabBullets: ["வாசலிலிருந்து வாசலுக்கு", "துணை இல்லை", "5 நிமிடத்தில்"],
      grabBtn: "Grab பதிவு",
      metHead: "MET (மானியம்)",
      metBadge: "மானியம்",
      metBullets: ["சக்கர நாற்காலி வசதி", "வாசல் முதல் வாசல்"],
      metBtn: "MET பதிவு",
      youSave: "சேமிப்பு",
      perTrip: "ஒரு பயணத்திற்கு",
      yearly: "≈ ஆண்டுக்கு $1,100 (மாதம் 4)",
      compareTitle: "ஒப்பீடு",
      whyMET: "MET ஏன் மலிவு",
      whyMETBody: "தகுதியுள்ள மூத்தோருக்கு அரசும் சமூகக் கூட்டாளரும் கட்டணத்தில் பெரும்பாலான பகுதியை ஏற்கின்றனர். மேலே காட்டிய சிறிய பங்கை மட்டுமே நீங்கள் கட்ட வேண்டும்.",
    },
    pv: {
      title: "சேவை வழங்குநரைத் தேர்ந்தெடுக்கவும்",
      subtitle: "மூன்று வழங்குநர்கள் உங்கள் பகுதியில் சேவை செய்கின்றனர். பின்னர் மாற்றலாம்.",
      serves: "உங்கள் பகுதி",
      coPay: "சுய பங்கு",
      response: "பதில்",
      choose: "தேர்வு",
      foot: "எப்போது வேண்டுமானாலும் வழங்குநரை மாற்றலாம்.",
    },
    ap: {
      sentTo: "உறுதி செய்யப்பட்டது:",
      reassure: "ஓட்டுநரும் துணையும் ஒதுக்கப்பட்டுள்ளனர். ஏற்றுவதற்கு முந்திய இரவே நினைவூட்டல் அனுப்பப்படும்.",
      ref: "குறிப்பு",
      view: "பயண நிலை",
      addCal: "நாள்காட்டியில் சேர்",
      whatNext: "அடுத்து",
      n1: "வழங்குநர் விண்ணப்பத்தை உறுதி செய்துவிட்டார்",
      n2: "ஓட்டுநரும் துணையும் ஒதுக்கப்பட்டனர்",
      n3: "முந்திய இரவே நினைவூட்டல் + நேரடி கண்காணிப்பு",
    },
    tk: {
      title: "பயண நிலை",
      eta: "எதிர்பார்க்கப்படும்",
      drvAssigned: "ஓட்டுநர் ஒதுக்கப்பட்டார்",
      driver: "ஓட்டுநர்", escort: "துணை", vehicle: "வாகனம்",
      mapPlaceholder: "ஓட்டுநர் புறப்பட்டதும் வாழும் வரைபடம் இங்கே தோன்றும்.",
      notify: "வீட்டில் பாதுகாப்பாக சேர்ந்ததும் எனக்கு தெரிவி",
      notifySub: "அவர்கள் சேர்ந்ததும் SMS அனுப்புவோம்.",
      stages: [
        "விண்ணப்பம் அனுப்பப்பட்டது",
        "வழங்குநரால் உறுதி",
        "ஓட்டுநர் ஒதுக்கப்பட்டார்",
        "ஏற்றுமிடம் நோக்கி",
        "மூத்தவர் ஏறினார்",
        "மருத்துவமனை சேர்ந்தது",
      ],
      contact: "வழங்குநரைத் தொடர்புகொள்",
      cancel: "ரத்து செய்",
      reqAt: "கோரப்பட்டது",
      arr: "சேருவது",
    },
    hm: {
      hi: "காலை வணக்கம்,",
      caring: "பராமரிப்பு:",
      next: "அடுத்த பயணம்",
      nothing: "வரவிருக்கும் பயணம் இல்லை.",
      bookNew: "புதிய பயணம்",
      quick: "விரைவு செயல்கள்",
      checkElig: "தகுதி பார்",
      manageProf: "மூத்தவர் சுயவிவரம்",
      tips: "தேவையானவை",
      tip1Title: "எடுத்துச் செல்லவும்",
      tip1Body: "IC, சந்திப்பு கடிதம், மருந்து.",
      tip2Title: "துணைக்குச் சொல்லவும்",
      tip2Body: "அலர்ஜி, இயக்கக் கட்டுப்பாடு, செவிக்கருவி.",
      saved: "இவ்வாண்டு சேமிப்பு",
    },
    tl: { title: "உங்கள் பயணங்கள்", upcoming: "வரவிருக்கும்", past: "முந்தைய", empty: "இன்னும் பயணம் இல்லை." },
    pr: {
      title: "சுயவிவரம்",
      caregiver: "பராமரிப்பாளர்",
      senior: "உங்கள் பராமரிப்பில் உள்ள மூத்தவர்",
      lang: "மொழி",
      acc: "அணுகுதன்மை",
      bigText: "பெரிய எழுத்து",
      ack: "நன்றி",
      version: "Smarties demo · v0.4 · முன்மாதிரி",
      changeElig: "தகுதி மீள்சோதனை",
      eligNote: "மானிய மதிப்பீடு",
    },
    common: { step: "படி", progress: "முன்னேற்றம்", a11yBack: "பின்", cancel: "ரத்து", confirm: "உறுதி" },
  },
};

const LANGS = [
  { code: "en", short: "EN", long: "English" },
  { code: "zh", short: "中文", long: "中文" },
  { code: "ms", short: "BM", long: "Bahasa Melayu" },
  { code: "ta", short: "தமிழ்", long: "தமிழ்" },
];

const PROVIDERS = [
  {
    id: "touch",
    name: "TOUCH Community Services",
    initials: "T",
    bg: "#0B2545",
    fg: "#F6E7C5",
    serves: "Ang Mo Kio · Bishan · Toa Payoh",
    coPay: "$10–$14",
    response: "~6 min",
    note: "Wheelchair-accessible vans, Mandarin-speaking escorts.",
  },
  {
    id: "blossom",
    name: "Blossom Seeds",
    initials: "B",
    bg: "#1F7A4D",
    fg: "#E3F1E8",
    serves: "Sembawang · Yishun · AMK North",
    coPay: "$11–$15",
    response: "~9 min",
    note: "Community drivers trained in dementia care.",
  },
  {
    id: "hca",
    name: "HCA Hospice Care",
    initials: "H",
    bg: "#D4A24C",
    fg: "#0B2545",
    serves: "Island-wide for palliative",
    coPay: "$12–$16",
    response: "~12 min",
    note: "Specialised vehicles for palliative & home-bound seniors.",
  },
];

// deterministic mock state used across screens
const TRIP = {
  id: "MET-2A4F19",
  home: "234 Ang Mo Kio Ave 3",
  hospital: "Singapore General Hospital",
  date: "Wed 15 May",
  time: "9:00 AM",
  arr: "9:35 AM",
  driver: { name: "Mr. Tan", rating: 4.9, vehicle: "Toyota Hiace · SGW 8421C" },
  escort: { name: "Mei Ling" },
  // estimated savings
  grabLow: 70,
  grabHigh: 80,
  metPrice: 12,
  metOriginal: 40,
};

const SENIOR = {
  name: "Madam Lim Soo Hoon",
  age: 78,
  relation: "Mother",
  conditions: ["Mild diabetes", "Knee osteoarthritis"],
  mobility: "Walking aid",
};

const CAREGIVER = {
  name: "Wei Ming",
  caringFor: "Madam Lim",
};

window.AppData = { TRANSLATIONS, LANGS, PROVIDERS, TRIP, SENIOR, CAREGIVER };
